### ISSUE TITLE
System.NullReferenceException: when installing on Visual Studio Enterprise 2017

### ISSUE THREAD

**Issue by vladlee098** [Microsoft/vs-tools-for-ai#1]
[VSIXInstaller_c7388073-99e5-4c83-b305-9b3b49e167ad.log](https://github.com/Microsoft/vs-tools-for-ai/files/1476377/VSIXInstaller_c7388073-99e5-4c83-b305-9b3b49e167ad.log)

**Comment by shishaochen** [comment]
@vladlee098 Checking your log, this is a known issue talked in Visual Studio Developer Community at [vsixinstaller.exe can't install extensions when Visual Studio Build Tools 2017 are installed](https://developercommunity.visualstudio.com/content/problem/32018/vsixinstallerexe-cant-install-extensions-when-visu.html).

Supposing your computer has Internet connection, the easiest installation way is:
1. Open the Visual Studio client you like, then click menu item **Tools**> **Extensions and Updates** 
2. **Search** in upper right-hand corner for "Tools for AI"
3. Select **Visual Studio Tools for AI**
4. Click **Download**

If you insist on downloading VSIX and install it locally, you may call %VSINSTALLDIR%\Common7\IDE\VSIXInstaller.exe in CMD with explicit argument telling which Visual Studio instance to install. Details can be found at [here](https://developercommunity.visualstudio.com/content/problem/32018/vsixinstallerexe-cant-install-extensions-when-visu.html).

**Comment by vladlee098** [comment]
Thank you, it worked
