### ISSUE TITLE
Not available on VSIX?

### ISSUE THREAD

**Issue by v-deken** [Microsoft/vs-tools-for-ai#13]
Attempting to follow the installation instructions to install this package from within VS2017 fails - the package doesn't appear to be available when searching for it in the Extensions and Updates dialog:
![image](https://user-images.githubusercontent.com/38538465/39884039-6ddb3588-543d-11e8-80c5-8dd0b0076035.png)
The VSIX package is available for download, however, from the Visual Studio Marketplace.

**Comment by squirrelsc** [comment]
It looks you are searching in installed things. Click "online" on left pane and try again.

**Comment by v-deken** [comment]
It did indeed, and, embarrassingly, you were right. All set, and thanks!
