### ISSUE TITLE
Unauthorized when calling Cognitive Service API

### ISSUE THREAD

**Issue by jwood803** [Microsoft/vs-tools-for-ai#15]
Created a Computer Vision project with the VS Tools for AI extension after creating the service in the Azure Portal. Putting the API key and (I assume) the correct location, I'm still getting an unauthorized exception. I even copied both keys from the AI Tools section of the Server window and still get this error. Am I setting something wrong?

![image](https://user-images.githubusercontent.com/1578160/40125106-1611a868-58f8-11e8-8059-554467ba7504.png)

**Comment by linmajia** [comment]
@jwood803 , thank you very much for the feedback.

This is a known issue in the Computer Vision application template. Please open the ComputerVisionApiExtensions.cs, and add a line of code "this.AzureRegion = GetRegion(region);"  in the ComputerVisionApiExtensions class's constructor:

![image](https://user-images.githubusercontent.com/9329359/40458469-bd2f40ba-5f2e-11e8-9045-e74d335982a8.png)

**Comment by jwood803** [comment]
Thanks, @linmajia! Just tried that and all is now working!
