### ISSUE TITLE
CNTK .NET support

### ISSUE THREAD

**Issue by Sam7** [Microsoft/vs-tools-for-ai#2]
Great to see Microsofts commitment to AI. MS has always pioneered the idea that serving developers should be a huge priority.

And as much as I appreciate that you're supporting Python and Tensorflow as they are the industry standard, I'd love to see much more integrated tools with CNTK .NET in a way to draw in the average c# developer. There is a huge **potential** here.

Another thought...
Just as 3D rendering used to be a developers task (remember Pov Ray 😄) and is now all achieved through very comprehensive editors.
I'm confident AI will go the same way, so get your ducks in a row ;)

Thanks for the great work you're doing here!

**Comment by chris-lauren** [comment]
Thanks for your feedback! Agreed that .net support is important...have you seen the new c# bindings for cntk https://docs.microsoft.com/en-us/cognitive-toolkit/using-cntk-with-csharp ?

**Comment by Sam7** [comment]
@chris-lauren Yes I've been playing with those, but the current C# API is not super well documented yet, with very view examples. That's why I'd love to have a plugin that supports setting up new experiments.
