### ISSUE TITLE
VS (15.7.3 and 15.8 Preview 2) uses guid as class name for ONNX model exported from customvision.ai

### ISSUE THREAD

**Issue by tamirdresher** [Microsoft/vs-tools-for-ai#21]
The issue was originally posted here: https://developercommunity.visualstudio.com/content/problem/266122/vs-158-preview-2-uses-guid-as-class-name-for-onnx.html 

Even after changing the onnx file name, VS 15.8 preview 2 uses a guid as a class name for ONNX models exported and downloaded from customvision.ai

Steps to repeat:
- Set customvision.ai project type to general (compact) domain
- Upload images and train model
- Export and download ONNX model
- Import ONNX model in Visual Studio

Expected result: allow user to enter a readable name or use the project name from customvision.ai instead of a guid as a classname

**Comment by linmajia** [comment]
@tamirdresher , thank you very much for the feedback.

Actually, the functionality you used is provided by VS 2017 directly instead of our extension. We also noticed this issue and have reported it to the corresponding team.
