### ISSUE TITLE
Submit job problems on macOS

### ISSUE THREAD

**Issue by 00yk** [Microsoft/vs-tools-for-ai#23]
When I submitting a job, it comes out the error message: The terminal process command '/bin/zsh ~/.vscode/extensions/ms-toolsai.vscode-ai-0.1.9/out/scripts/pythonTerminal.sh' failed to launch (exit code: 127).

And when I type the above command in the command line, it showed me "pythonTerminal.sh" did not handle directory paths with spaces correctly.

Like, "/Applications/VMware Fusion.app/Contents/Public" seems to miss a backslash.

**Comment by fucknamel** [comment]
I've met this problem, can you tell me how to solve this problem? Thank you!

**Comment by linmajia** [comment]
@fucknamel , please refer to https://github.com/Microsoft/vscode-tools-for-ai/issues/38
