### ISSUE TITLE
LinuxVM Job List: Error - ssh failed, exit code: 123

### ISSUE THREAD

**Issue by fucknamel** [Microsoft/vs-tools-for-ai#27]
It shows "Error - ssh failed, exit code: 123" after I successfully submited my job. However, I can ssh my VM on my terminal. And it shows "exit code: 127" in the same situation sometimes.

**Comment by linmajia** [comment]
@fucknamel , thank you very much for the feedback.

Are you using VS Code Tools for AI?

**Comment by fucknamel** [comment]
Yes. I haven't found the solution for a long time.

**Comment by linmajia** [comment]
Since this issue is related to VS Code Tools for AI, move it to https://github.com/Microsoft/vscode-tools-for-ai/issues/40
