### ISSUE TITLE
Problem Sample Explorer: Install "Classifying Iris" sample

### ISSUE THREAD

**Issue by pkwdev** [Microsoft/vs-tools-for-ai#28]
I tried multiple attempts and kept having this error, asking me to have account name to be between 3 to 32 characters long.  But, the aAccount name is already between 3 to 32 characters--DrDataSciExperiment.  preciate if you can help.  Thank you.  

Messages below is from output window.

Retrieving resource groups ...
AMLCli: Executing 'az group list -o json'.
AMLCli: Execution succeeded.
>Done.
Retrieving accounts ...
AMLCli: Executing 'az ml account experimentation list -g "AI1" -o json'.
AMLCli: Execution succeeded.
>Done.
Retrieving workspaces ...
AMLCli: Executing 'az ml workspace list -a "DrDataSciExperiment" -g "AI1" -o json'.
AMLCli: Execution succeeded.
>Done.
AMLCli: Executing 'az ml project create -n ClassifyingIris_074 -u "https://github.com/Azure/MachineLearningSamples-Iris" --path C:\MachineLearn -a "DrDataSciExperiment" -w "DrDataSciWorkSpace" -g "AI1" -l "australiaeast" -o json'.
ERROR: Account name must be between 3 and 32 characters long. Its first character has to be alphanumeric, and the rest may contain hyphens and underscores.

**Comment by linmajia** [comment]
@pkwdev , thank you very much for the feedback.

Tools for AI calls Azure ML SDK to enlist the examples. There is an error message in your post: "ERROR: Account name must be between 3 and 32 characters long. Its first character has to be alphanumeric, and the rest may contain hyphens and underscores." Please verify whether your Azure ML account name  begins with lowercase letter and meets the foregoing requirements.

Thanks.

**Comment by pkwdev** [comment]
Thank you very much for your help.  It worked great now when I changed the first letter to lower case.

Thanks again.
