### ISSUE TITLE
Input/Output directories lists in Submit Job dialog have wrong entries

### ISSUE THREAD

**Issue by vassilyl** [Microsoft/vs-tools-for-ai#3]
"Input directories" and "Output directories" list lists of Submit job dialog show entries as $AZ_BATCHAI_MOUNT_ROOT_<Id>. The should be $AZ_BATCHAI_INPUT_<Id> and $AZ_BATCHAI_OUTPUT_<Id> correspondingly.

**Comment by linmajia** [comment]
Thank you very much for the feedback, vassilyl! This issue will be fixed in the new release. Your jobs won't be affected by such wrong display because correct input/output values are passed during submission.

**Comment by linmajia** [comment]
Fixed in version 0.3.3.0 .
