### ISSUE TITLE
Error opening project on VS 2017 

### ISSUE THREAD

**Issue by johansenmic** [Microsoft/vs-tools-for-ai#5]
I have installed newest AI tools version 0.3.3.0 on VS 2017 (15.5.6). When I open an existing project I get the error "Save view failed with the following error: Type 'Microsoft.VSDesigner.ServerExplorer.Node' in assembly 'Microsoft.VisualStudio.ServerExplorer, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f711d50a3a' is not marked as serializable. Make sure the view name is a valid file name.

If I disable AI tools the error does not appear again.

**Comment by megyer** [comment]
I have a same issue.

**Comment by linmajia** [comment]
Fixed in 0.4.0.620119 .
